version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework:*"
      spring-cloud-stream:
        patterns:
          - "org.springframework.cloud:spring-cloud-stream*"
      wiremock:
        patterns:
          - "org.wiremock:*"
      rest-assured:
        patterns:
          - "io.rest-assured:*"
      testing:
        patterns:
          - "org.junit.jupiter:*"
          - "org.junit.vintage:*"
          - "org.assertj:*"
          - "org.mockito:*"
