/*
 * Copyright 2013-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sh.stubborn.contract.verifier.dsl.wiremock;

import com.github.tomakehurst.wiremock.extension.Parameters;
import com.github.tomakehurst.wiremock.http.Request;
import com.github.tomakehurst.wiremock.matching.MatchResult;
import com.github.tomakehurst.wiremock.matching.RequestMatcherExtension;

/**
 * Backward-compatibility alias for {@link SpringCloudContractRequestMatcher} that
 * responds to the legacy {@code "spring-cloud-contract"} matcher name. Existing stubs
 * generated by Spring Cloud Contract embed this name; registering both extensions ensures
 * those stubs continue to work side-by-side with new {@code "stubborn-contract"} stubs.
 *
 * @author Marcin Grzejszczak
 * @since 0.1.0
 */
public class SpringCloudContractRequestMatcherCompat extends RequestMatcherExtension {

	/**
	 * Legacy transformer name used by Spring Cloud Contract-generated stubs.
	 */
	public static final String NAME = "spring-cloud-contract";

	private final SpringCloudContractRequestMatcher delegate = new SpringCloudContractRequestMatcher();

	@Override
	public MatchResult match(Request request, Parameters parameters) {
		return this.delegate.match(request, parameters);
	}

	@Override
	public String getName() {
		return NAME;
	}

}
