[[how-to-build-spring-cloud-contract]]
= How to Build Stubborn Contract

[[cloning-the-repository-on-windows]]
== Cloning the repository on Windows

While cloning this project on Windows, some files in the git repository may exceed the Windows maximum file path limit of 255 characters, which may
result in an incorrectly (probably partially) checked out repository.

To resolve this issue, you can set the `core.longPaths` attribute to `true` or clone the Stubborn Contract repository.

To set the `core.longPaths` attribute to `true`, you have three options:

- Change it for all users of the machine (doing so requires administrator privileges):


[source,bash]
----
git config --system core.longPaths true
git clone https://github.com/spring-cloud/spring-cloud-contract.git
----

- Change it for the current user (no administrative privileges required):

[source,bash]
----
git config --global core.longPaths true
git clone https://github.com/spring-cloud/spring-cloud-contract.git
----

- Change for just this repository (administrative privileges depend on where the repository is being cloned to):

[source,bash]
----
git clone -c core.longPaths=true https://github.com/spring-cloud/spring-cloud-contract.git
----

IMPORTANT: You need to have all the necessary Groovy plugins
installed for your IDE to properly resolve the sources. For example, in
Intellij IDEA, having both the Eclipse Groovy Compiler Plugin and the GMavenPlus Intellij
Plugin results in properly imported project.

IMPORTANT: Stubborn Contract builds Docker images. Remember to
have Docker installed.

IMPORTANT: If you want to run the build in offline mode, you must have Maven 3.5.2+ installed.

[[project-structure]]
== Project structure

The following listing shows the Stubborn Contract folder structure:

```
├── config
├── docker
├── samples
├── scripts
├── specs
├── stubborn-dependencies
├── spring-cloud-contract-shade
├── stubborn-starters
├── stubborn-stub-runner
├── stubborn-stub-runner-boot
├── spring-cloud-contract-tools
├── stubborn-verifier
├── stubborn-wiremock
└── tests
```

The following list describes each of the top-level folders in the project structure:

- `config`: Folder contains setup for Spring Cloud Release Tools automated release process
- `docker`: Folder contains docker images
- `scripts`: Contains scripts to build and test `Stubborn Contract` with Maven, Gradle
- `specs`: Contains specifications for the Contract DSL.
- `stubborn-dependencies`: Contains Stubborn Contract BOM
- `spring-cloud-contract-shade`: Shaded dependencies used by the plugins
- `stubborn-starters`: Contains Stubborn Contract Starters
- `spring-cloud-contract-spec`: Contains specification modules (contains concept of a Contract)
- `stubborn-stub-runner`: Contains Stub Runner related modules
- `stubborn-stub-runner-boot`: Contains Stub Runner Boot app
- `spring-cloud-contract-tools`: Gradle and Maven plugin for `Stubborn Contract Verifier`
- `stubborn-verifier`: Core of the `Stubborn Contract Verifier` functionality
- `stubborn-wiremock`: All WireMock related functionality
- `tests`: Integration tests for different messaging technologies

[[commands]]
== Commands

To build the core functionality together with the Maven Plugin, you can run the following
command:

```
./mvnw clean install -P integration
```

Calling that function builds the core, the Maven plugin, and the Gradle plugin.

To build only the Gradle Plugin, you can run the following commands:

```
cd spring-cloud-contract-tools/stubborn-gradle-plugin
./gradlew clean build
```

[[helpful-scripts]]
== Helpful scripts

We provide a couple of helpful scripts to build the project.

To build the project in parallel (by default, it uses four cores, but you can change it),
run the following command:

```
./scripts/parallelBuild.sh
```

To use eight 8 cores, run the following command:

```
CORES=8 ./scripts/parallelBuild.sh
```

To build the project without any integration tests (by default, this uses one core), run
the following command:

```
./scripts/noIntegration.sh
```

To use eight cores, run the following command:

```
CORES=8 ./scripts/noIntegration.sh
```

To generate the documentation (for both the root project and the maven plugin), run the
following command:

```
./scripts/generateDocs.sh
```
