/*
 * Copyright 2013-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sh.stubborn.contract.verifier.messaging.boot;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Reproduces
 * <a href="https://github.com/stubborn-sh/stubborn-contract/issues/184">#184</a>.
 *
 * <p>
 * The {@code spring-boot-autoconfigure-processor} must generate
 * {@code META-INF/spring-autoconfigure-metadata.properties} at compile time so Spring
 * Boot can order and back off the messaging auto-configurations through
 * {@link org.springframework.boot.autoconfigure.AutoConfigureBefore @AutoConfigureBefore}
 * / {@link org.springframework.boot.autoconfigure.AutoConfigureOrder @AutoConfigureOrder}
 * — separate from the runtime {@code @Conditional} checks. Without this metadata,
 * {@code ContractVerifierIntegrationConfiguration} (guarded only by the ubiquitous
 * {@code @ConditionalOnClass(Message.class)}) wires into contexts that have no Spring
 * Integration setup, failing with a missing {@code MessageVerifierSender} bean.
 *
 * <p>
 * Before the fix the resource is absent from the module output (the annotation processor
 * never runs, because the parent pom's explicit {@code annotationProcessorPaths}
 * suppresses classpath-discovered processors), so these tests fail. After wiring the
 * processor into the compiler's {@code annotationProcessorPaths} the resource is
 * generated and packaged.
 */
class AutoConfigureMetadataTests {

	private static final String RESOURCE = "/META-INF/spring-autoconfigure-metadata.properties";

	private static final String INTEGRATION_CONFIG = "sh.stubborn.contract.verifier.messaging.integration.ContractVerifierIntegrationConfiguration";

	private static final String NOOP_CONFIG = "sh.stubborn.contract.verifier.messaging.noop.NoOpContractVerifierAutoConfiguration";

	@Test
	void autoconfigure_metadata_is_generated_and_packaged() throws IOException {
		Properties metadata = loadMetadata();
		assertThat(metadata)
			.as("%s must be generated by spring-boot-autoconfigure-processor and packaged into the jar", RESOURCE)
			.isNotEmpty();
	}

	@Test
	void integration_configuration_is_ordered_before_the_noop_configuration() throws IOException {
		Properties metadata = loadMetadata();
		assertThat(metadata.getProperty(INTEGRATION_CONFIG + ".AutoConfigureBefore"))
			.as("@AutoConfigureBefore ordering metadata for ContractVerifierIntegrationConfiguration")
			.isEqualTo(NOOP_CONFIG);
		assertThat(metadata.getProperty(INTEGRATION_CONFIG + ".ConditionalOnClass"))
			.as("@ConditionalOnClass metadata for ContractVerifierIntegrationConfiguration")
			.contains("org.springframework.messaging.Message");
		assertThat(metadata.getProperty(NOOP_CONFIG + ".AutoConfigureOrder"))
			.as("@AutoConfigureOrder metadata for NoOpContractVerifierAutoConfiguration")
			.isEqualTo(String.valueOf(Integer.MAX_VALUE));
	}

	private Properties loadMetadata() throws IOException {
		Properties properties = new Properties();
		try (InputStream input = getClass().getResourceAsStream(RESOURCE)) {
			assertThat(input).as("%s must be present on the classpath (module output)", RESOURCE).isNotNull();
			properties.load(input);
		}
		return properties;
	}

}
