<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>sh.stubborn</groupId>
	<artifactId>stubborn-contract-docs</artifactId>
	<parent>
		<groupId>sh.stubborn</groupId>
		<artifactId>stubborn-contract-parent</artifactId>
		<version>0.1.0-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>
	<packaging>jar</packaging>
	<name>Stubborn Contract Docs</name>
	<description>Stubborn Contract Reference Documentation</description>
	<properties>
		<!-- Don't deploy docs jar to Maven Central -->
		<maven-deploy-plugin-default.phase>none</maven-deploy-plugin-default.phase>
		<maven.install.skip>true</maven.install.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>sh.stubborn</groupId>
			<artifactId>stubborn-contract-verifier</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>
</project>
